// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alloc_svr.proto

package allocsvr

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Uid struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Version              uint64   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uid) Reset()         { *m = Uid{} }
func (m *Uid) String() string { return proto.CompactTextString(m) }
func (*Uid) ProtoMessage()    {}
func (*Uid) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb2aea015f488f67, []int{0}
}

func (m *Uid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uid.Unmarshal(m, b)
}
func (m *Uid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uid.Marshal(b, m, deterministic)
}
func (m *Uid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uid.Merge(m, src)
}
func (m *Uid) XXX_Size() int {
	return xxx_messageInfo_Uid.Size(m)
}
func (m *Uid) XXX_DiscardUnknown() {
	xxx_messageInfo_Uid.DiscardUnknown(m)
}

var xxx_messageInfo_Uid proto.InternalMessageInfo

func (m *Uid) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Uid) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type SectionIdArr struct {
	Val                  []uint64 `protobuf:"varint,1,rep,packed,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SectionIdArr) Reset()         { *m = SectionIdArr{} }
func (m *SectionIdArr) String() string { return proto.CompactTextString(m) }
func (*SectionIdArr) ProtoMessage()    {}
func (*SectionIdArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb2aea015f488f67, []int{1}
}

func (m *SectionIdArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SectionIdArr.Unmarshal(m, b)
}
func (m *SectionIdArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SectionIdArr.Marshal(b, m, deterministic)
}
func (m *SectionIdArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SectionIdArr.Merge(m, src)
}
func (m *SectionIdArr) XXX_Size() int {
	return xxx_messageInfo_SectionIdArr.Size(m)
}
func (m *SectionIdArr) XXX_DiscardUnknown() {
	xxx_messageInfo_SectionIdArr.DiscardUnknown(m)
}

var xxx_messageInfo_SectionIdArr proto.InternalMessageInfo

func (m *SectionIdArr) GetVal() []uint64 {
	if m != nil {
		return m.Val
	}
	return nil
}

//map[string][]SectionID => ip:{1,2,3}
type SeqNum struct {
	SeqNum               uint64                   `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Router               map[string]*SectionIdArr `protobuf:"bytes,2,rep,name=router,proto3" json:"router,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Version              uint64                   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SeqNum) Reset()         { *m = SeqNum{} }
func (m *SeqNum) String() string { return proto.CompactTextString(m) }
func (*SeqNum) ProtoMessage()    {}
func (*SeqNum) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb2aea015f488f67, []int{2}
}

func (m *SeqNum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeqNum.Unmarshal(m, b)
}
func (m *SeqNum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeqNum.Marshal(b, m, deterministic)
}
func (m *SeqNum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeqNum.Merge(m, src)
}
func (m *SeqNum) XXX_Size() int {
	return xxx_messageInfo_SeqNum.Size(m)
}
func (m *SeqNum) XXX_DiscardUnknown() {
	xxx_messageInfo_SeqNum.DiscardUnknown(m)
}

var xxx_messageInfo_SeqNum proto.InternalMessageInfo

func (m *SeqNum) GetSeqNum() uint64 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *SeqNum) GetRouter() map[string]*SectionIdArr {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *SeqNum) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*Uid)(nil), "allocsvr.Uid")
	proto.RegisterType((*SectionIdArr)(nil), "allocsvr.SectionIdArr")
	proto.RegisterType((*SeqNum)(nil), "allocsvr.SeqNum")
	proto.RegisterMapType((map[string]*SectionIdArr)(nil), "allocsvr.SeqNum.RouterEntry")
}

func init() { proto.RegisterFile("alloc_svr.proto", fileDescriptor_eb2aea015f488f67) }

var fileDescriptor_eb2aea015f488f67 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0xa2, 0xa9, 0x4e, 0x94, 0x96, 0x3d, 0x68, 0x28, 0x1e, 0x42, 0x4e, 0x3d, 0x48,
	0xc0, 0xd8, 0x83, 0x78, 0x2b, 0xa2, 0xe0, 0xa5, 0x60, 0x42, 0xcf, 0x25, 0x26, 0x03, 0x06, 0xd3,
	0xac, 0x9d, 0xfd, 0x83, 0xfd, 0x7e, 0x7e, 0x30, 0xd9, 0x4d, 0x4a, 0x63, 0x6f, 0xb3, 0x33, 0xef,
	0xcd, 0xbc, 0xdf, 0xc2, 0xb8, 0x68, 0x1a, 0x5e, 0xae, 0x85, 0xa6, 0xe4, 0x9b, 0xb8, 0xe4, 0xec,
	0xdc, 0x36, 0x84, 0xa6, 0xf8, 0x1e, 0xbc, 0x55, 0x5d, 0xb1, 0x09, 0x78, 0xaa, 0xae, 0x42, 0x27,
	0x72, 0x66, 0xa7, 0x99, 0x29, 0x59, 0x08, 0x23, 0x8d, 0x24, 0x6a, 0xde, 0x86, 0xae, 0xed, 0xee,
	0x9f, 0x71, 0x04, 0x97, 0x39, 0x96, 0xb2, 0xe6, 0xed, 0x5b, 0xb5, 0x20, 0x32, 0x5e, 0x5d, 0x34,
	0xa1, 0x13, 0x79, 0xc6, 0xab, 0x8b, 0x26, 0xfe, 0x75, 0xc0, 0xcf, 0x71, 0xbb, 0x54, 0x1b, 0x76,
	0x03, 0x23, 0x81, 0xdb, 0x75, 0xab, 0x36, 0xfd, 0x72, 0x5f, 0x74, 0x83, 0x39, 0xf8, 0xc4, 0x95,
	0x44, 0x0a, 0xdd, 0xc8, 0x9b, 0x05, 0xe9, 0x6d, 0xb2, 0xcf, 0x94, 0x74, 0xd6, 0x24, 0xb3, 0xe3,
	0x97, 0x56, 0xd2, 0x2e, 0xeb, 0xb5, 0xc3, 0x54, 0xde, 0xbf, 0x54, 0xd3, 0x77, 0x08, 0x06, 0x06,
	0x13, 0xea, 0x0b, 0x77, 0xf6, 0xe6, 0x45, 0x66, 0x4a, 0x76, 0x07, 0x67, 0xba, 0x68, 0x14, 0x5a,
	0x9c, 0x20, 0xbd, 0x1e, 0xde, 0x3b, 0xd0, 0x64, 0x9d, 0xe8, 0xc9, 0x7d, 0x74, 0xd2, 0x67, 0x08,
	0x16, 0x46, 0x93, 0x23, 0x69, 0x24, 0x36, 0x87, 0xf1, 0x2b, 0xca, 0xf2, 0x73, 0x89, 0x3f, 0xb2,
	0xa7, 0xbb, 0x3a, 0x2c, 0x59, 0xd5, 0xd5, 0x74, 0x72, 0xcc, 0x10, 0x9f, 0x7c, 0xf8, 0xf6, 0xc7,
	0x1f, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xea, 0x34, 0x97, 0x84, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AllocServerClient is the client API for AllocServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AllocServerClient interface {
	FetchNextSeqNum(ctx context.Context, in *Uid, opts ...grpc.CallOption) (*SeqNum, error)
}

type allocServerClient struct {
	cc *grpc.ClientConn
}

func NewAllocServerClient(cc *grpc.ClientConn) AllocServerClient {
	return &allocServerClient{cc}
}

func (c *allocServerClient) FetchNextSeqNum(ctx context.Context, in *Uid, opts ...grpc.CallOption) (*SeqNum, error) {
	out := new(SeqNum)
	err := c.cc.Invoke(ctx, "/allocsvr.AllocServer/FetchNextSeqNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AllocServerServer is the server API for AllocServer service.
type AllocServerServer interface {
	FetchNextSeqNum(context.Context, *Uid) (*SeqNum, error)
}

// UnimplementedAllocServerServer can be embedded to have forward compatible implementations.
type UnimplementedAllocServerServer struct {
}

func (*UnimplementedAllocServerServer) FetchNextSeqNum(ctx context.Context, req *Uid) (*SeqNum, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchNextSeqNum not implemented")
}

func RegisterAllocServerServer(s *grpc.Server, srv AllocServerServer) {
	s.RegisterService(&_AllocServer_serviceDesc, srv)
}

func _AllocServer_FetchNextSeqNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllocServerServer).FetchNextSeqNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allocsvr.AllocServer/FetchNextSeqNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllocServerServer).FetchNextSeqNum(ctx, req.(*Uid))
	}
	return interceptor(ctx, in, info, handler)
}

var _AllocServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "allocsvr.AllocServer",
	HandlerType: (*AllocServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchNextSeqNum",
			Handler:    _AllocServer_FetchNextSeqNum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alloc_svr.proto",
}
